---
title: "Assignment7"
format: html
editor: visual
---


```{r}
library(tidyverse)
library(data.table) ## For the fread function
library(lubridate)

source("sepsis_monitor_functions.R")
```

```{r}
library(tictoc)
library(data.table)

tic()
makeSepsisDataset(n = 50, read_fn = "fread")
toc() #10.58 sec elapsed

# create sepsis dataset with 50 patients using read_delim
tic()
makeSepsisDataset(n = 50, read_fn = "read_delim")
toc() #26.32 sec

tic()
makeSepsisDataset(n = 100, read_fn = "fread")
toc() #21.38 sec

tic()
makeSepsisDataset(n = 100, read_fn = "read_delim")
toc() #49.27 sec

tic()
makeSepsisDataset(n = 500, read_fn = "fread")
toc() #104.05 sec elapsed

tic()
makeSepsisDataset(n = 500, read_fn = "read_delim")
toc() #213.661 sec

read_delim_avg <- mean(26.32,49.27,213.661)
fread_avg <- mean(10.58,21.38,104.05) 

```

```{r}
library(googledrive)

df <- makeSepsisDataset()

# We have to write the file to disk first, then upload it
df %>% write_csv("sepsis_data_temp.csv")

# Uploading happens here
sepsis_file <- drive_put(media = "sepsis_data_temp.csv", 
          path = "https://drive.google.com/drive/u/0/folders/1S0sZy2AG2FRvcGjbUZ43hf2nAdl62KG5",
          name = "sepsis_data.csv")

# Set the file permissions so anyone can download this file.
sepsis_file %>% drive_share_anyone()
```


```{r}
## All data up until now
## Calling drive_deauth() prevents R from trying to authenticate via a browser
## This is needed to make the GitHub Action work
drive_deauth()
file_link <- "https://drive.google.com/file/d/1nJ0vLIscngULZ01rVF78wbObJbJiwmqH/view?usp=sharing"

## All data up until now
new_data <- updateData(file_link)

## Include only most recent data
most_recent_data <- new_data %>%
  group_by(PatientID) %>%
  filter(obsTime == max(obsTime))

```

